image: Visual Studio 2015

before_build:
- ps: nuget install Microsoft.CodeAnalysis.Analyzers -Version 1.2.0-beta2
- ps: nuget install Microsoft.CodeAnalysis.Common -Version 2.0.0-beta3
- ps: nuget install IKVM -Version 8.1.5717

install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
