image: Visual Studio 2015

before_build:
- ps: Install-Package Microsoft.CodeAnalysis.Analyzers ("-Version 1.2.0-beta2")
- ps: Install-Package Microsoft.CodeAnalysis.Common ("-Version 2.0.0-beta3")

install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
